version: '2'
services:
  ssh-agent:
    image: "docksal/ssh-agent"
    volumes:
      - ssh-agent:/.ssh-agent
    labels:
      # make it a global service
      io.rancher.scheduler.global: 'true'
  rancheros-provisioner:
    image: "kenwenzel/rancheros-provisioner"
    labels:
      io.rancher.container.start_once: true
      # make it a global service
      io.rancher.scheduler.global: 'true'
    volumes:
      - /usr/bin:/host/usr/bin
      - /root:/host/root
volumes:
  ssh-agent:
    external: true
