version: '2'
services:
  ssh-agent:
    image: "kenwenzel/ssh-agent"
    volumes:
      - /root:/host
      - ssh-agent:/.ssh-agent
    environment:
      - CREATE_KEY=1
    labels:
      # make it a global service
      io.rancher.scheduler.global: 'true'
  rancheros-provisioner:
    image: "kenwenzel/rancheros-provisioner"
    labels:
      io.rancher.container.start_once: 'true'
      # make it a global service
      io.rancher.scheduler.global: 'true'
    volumes:
      - /usr/bin:/host/usr/bin
      - /root:/host/root
    environment:
      GIT_CONFIG_DEFAULT: |
        ["ssh://docker@git.iwu.fraunhofer.de:29418"]
           insteadOf = git://git.iwu.fraunhofer.de
           insteadOf = http://git.iwu.fraunhofer.de
volumes:
  ssh-agent:
    external: true
